/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author clementraphaell
 */
public class InterfaceGraphiqueModifierComp extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphiqueModifierComp
     */
    public InterfaceGraphiqueModifierComp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelModifComp = new javax.swing.JLabel();
        labelCompModifComp = new javax.swing.JLabel();
        comboBoxCompModifComp = new javax.swing.JComboBox<>();
        labelNomModifComp = new javax.swing.JLabel();
        textFieldNomModifComp = new javax.swing.JTextField();
        labelCodeModifComp = new javax.swing.JLabel();
        textFieldCodeModifComp = new javax.swing.JTextField();
        labelDescrModifComp = new javax.swing.JLabel();
        textFieldDescrModifComp = new javax.swing.JTextField();
        buttonModifModifComp = new javax.swing.JButton();
        buttonRetourModifComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelModifComp.setText("Modifier Compétences");

        labelCompModifComp.setText("Compétences :");

        comboBoxCompModifComp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        labelNomModifComp.setText("Nom :");

        labelCodeModifComp.setText("Code :");

        labelDescrModifComp.setText("Description :");

        textFieldDescrModifComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldDescrModifCompActionPerformed(evt);
            }
        });

        buttonModifModifComp.setText("Modifier");

        buttonRetourModifComp.setText("Retour");
        buttonRetourModifComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourModifCompMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(labelModifComp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelCompModifComp)
                                    .addComponent(labelNomModifComp)
                                    .addComponent(labelCodeModifComp)
                                    .addComponent(labelDescrModifComp))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCompModifComp, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(textFieldNomModifComp, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                                            .addComponent(textFieldCodeModifComp))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(textFieldDescrModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonModifModifComp)
                .addGap(62, 62, 62)
                .addComponent(buttonRetourModifComp))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelModifComp)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCompModifComp)
                    .addComponent(comboBoxCompModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNomModifComp)
                    .addComponent(textFieldNomModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCodeModifComp)
                    .addComponent(textFieldCodeModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(labelDescrModifComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldDescrModifComp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonModifModifComp)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonRetourModifComp))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldDescrModifCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldDescrModifCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldDescrModifCompActionPerformed

    private void buttonRetourModifCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourModifCompMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiqueCompetences  Competences = new InterfaceGraphiqueCompetences();
        this.dispose();
        Competences.setVisible(true);
    }//GEN-LAST:event_buttonRetourModifCompMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueModifierComp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphiqueModifierComp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonModifModifComp;
    private javax.swing.JButton buttonRetourModifComp;
    private javax.swing.JComboBox<String> comboBoxCompModifComp;
    private javax.swing.JLabel labelCodeModifComp;
    private javax.swing.JLabel labelCompModifComp;
    private javax.swing.JLabel labelDescrModifComp;
    private javax.swing.JLabel labelModifComp;
    private javax.swing.JLabel labelNomModifComp;
    private javax.swing.JTextField textFieldCodeModifComp;
    private javax.swing.JTextField textFieldDescrModifComp;
    private javax.swing.JTextField textFieldNomModifComp;
    // End of variables declaration//GEN-END:variables
}
