/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author clementraphaell
 */
public class InterfaceGraphiqueCompetences extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceGraphiqueCompetences
     */
    public InterfaceGraphiqueCompetences() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCompComp = new javax.swing.JLabel();
        labelListeComp = new javax.swing.JLabel();
        tableComp = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        buttonAjouteComp = new javax.swing.JButton();
        buttonModifComp = new javax.swing.JButton();
        buttonSuppComp = new javax.swing.JButton();
        buttonSauvComp = new javax.swing.JButton();
        buttonRetourComp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelCompComp.setText("Compétences");

        labelListeComp.setText("Liste :");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nom", "Libelle"
            }
        ));
        tableComp.setViewportView(jTable1);

        buttonAjouteComp.setText("Ajouter");
        buttonAjouteComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonAjouteCompMouseClicked(evt);
            }
        });

        buttonModifComp.setText("Modifier");
        buttonModifComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonModifCompMouseClicked(evt);
            }
        });

        buttonSuppComp.setText("Supprimer");
        buttonSuppComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuppCompActionPerformed(evt);
            }
        });

        buttonSauvComp.setText("Sauvegarder");
        buttonSauvComp.setEnabled(false);
        buttonSauvComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSauvCompActionPerformed(evt);
            }
        });

        buttonRetourComp.setText("Retour");
        buttonRetourComp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRetourCompMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(194, 194, 194)
                                .addComponent(labelCompComp))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tableComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelListeComp)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(buttonAjouteComp)
                                        .addGap(72, 72, 72)
                                        .addComponent(buttonModifComp)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(buttonSuppComp)
                                        .addGap(9, 9, 9)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(buttonSauvComp)
                        .addGap(41, 41, 41)
                        .addComponent(buttonRetourComp)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCompComp)
                .addGap(44, 44, 44)
                .addComponent(labelListeComp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tableComp, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAjouteComp)
                    .addComponent(buttonModifComp)
                    .addComponent(buttonSuppComp))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSauvComp)
                    .addComponent(buttonRetourComp))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSuppCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuppCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSuppCompActionPerformed

    private void buttonSauvCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSauvCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSauvCompActionPerformed

    private void buttonAjouteCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonAjouteCompMouseClicked
        // TODO add your handling code here:
        interfaceGraphiqueAjouteComp AjoutComp = new interfaceGraphiqueAjouteComp();
        this.dispose();
        AjoutComp.setVisible(true);
        
    }//GEN-LAST:event_buttonAjouteCompMouseClicked

    private void buttonModifCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonModifCompMouseClicked
        // TODO add your handling code here:
        InterfaceGraphiqueModifierComp ModifComp = new InterfaceGraphiqueModifierComp();
        this.dispose();
        ModifComp.setVisible(true);
    }//GEN-LAST:event_buttonModifCompMouseClicked

    private void buttonRetourCompMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRetourCompMouseClicked
        // TODO add your handling code here:
        interfaceGraphiqueAccueil Accueil = new interfaceGraphiqueAccueil();
        this.dispose();
        Accueil.setVisible(true);
    }//GEN-LAST:event_buttonRetourCompMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCompetences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCompetences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCompetences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceGraphiqueCompetences.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceGraphiqueCompetences().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAjouteComp;
    private javax.swing.JButton buttonModifComp;
    private javax.swing.JButton buttonRetourComp;
    private javax.swing.JButton buttonSauvComp;
    private javax.swing.JButton buttonSuppComp;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelCompComp;
    private javax.swing.JLabel labelListeComp;
    private javax.swing.JScrollPane tableComp;
    // End of variables declaration//GEN-END:variables
}
